- tools/backups2datalad.py
> Address TODOs in backups2datalad.py

- tools/backups2datalad-cron
- tools/backups2datalad.py
> Skip assets if metadata is unchanged

- tools/backups2datalad.py
> Skip creating GitHub sibling if already exists

- tools/backups2datalad.py
Fixes a bug encountered by @yarikoptic.
> Ignore pre-#15 assets.json

- tools/backups2datalad.py
> Add --pdb option to backups2datalad.py

- tools/backups2datalad.py
Closes #20.
The resulting descriptions can be seen on the repositories under https://github.com/dandisets-testing.
> Set repositories' descriptions and URLs

- tools/backups2datalad.py
> Delete dest file before downloading

- tools/backups2datalad.py
> Add `--exclude REGEX` option for excluding Dandisets

- tools/backups2datalad.py
> Retry Girder requests that result in 5xx responses

- tools/backups2datalad.py
> Use fscacher to memoize hashes

- tools/backups2datalad.py
> Update backups2datalad.py to use dandi-api

- tools/backups2datalad.py
Only for testing, not for merging.
> Add debugging statements for identifying slowness

- tools/backups2datalad.py
> Compactify commit messages

- tools/use-new-urls.py
> Script for updating Dataset asset URLs

- tools/backups2datalad.py
> Update for dandi-cli#660

- tools/backups2datalad.py
> Ensure commit date is no earlier than previous commit date

- .github/workflows/test.yml
- .gitignore
- tools/backups2datalad-cron
- tools/backups2datalad.py
- tools/backups2datalad.req.txt
- tools/mypy.ini
- tools/noxfile.py
- tools/test_backups2datalad.py
> Create tags for published Dandiset versions

- tools/backups2datalad.py
Ref: https://github.com/dandi/dandisets/issues/58#issuecomment-897925118
> Push new version tags

- .github/workflows/test.yml
> Install git-annex in tests

- tools/backups2datalad.py
- tools/noxfile.py
- tools/test_backups2datalad.py
> Adjust version commit detection logic

- tools/backups2datalad.py
- tools/backups2datalad.req.txt
- tools/test_backups2datalad.py
> Ensure latest version tag is merged into master branch

- tools/backups2datalad.py
- tools/test_backups2datalad.py
Closes #70.
~Please merge #68 before this PR, after which I suspect I will have to resolve some merge conflicts.~
> Set custom commit author

- tools/backups2datalad.py
- tools/chdefbranch.py
- tools/test_backups2datalad.py
> Use "draft" as default branch name

- tools/test_backups2datalad.py
> Delete test Dandiset after testing
